### ISSUE TITLE
multiple calls to stop cause error and fix

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#110]
when calling p.stop from pynn (but for all frontends) multiple times, it tries to close the machine_allocation_controller multiple times, which after the first time, causes an error message about the spalloc connection already being closed.

adding line
"self._machine_allocation_controller = None" under self._machine_allocation_controller.close() on line 1833:

https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/spinnaker_main_interface.py#L1833

solves the issue, as it deallocates the controller once closed, which is the safer thing to do anyhows.

**Comment by Christian-B** [comment]
Fixed.

Accidental push straight to master.

Also added unit test:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/unittests/test_spinnaker_main_interface.py
