### ISSUE TITLE
live buffering bust currently

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#162]
when using live buffering, a issue occurs during the reception of packets due to a mismatch of data. Currently avoided via the auto pause and resume functionality.

**Comment by Christian-B** [comment]
Replicated by:
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/test_if_curr_exp_live_buffers/test_synfire_if_curr_exp.py
