### ISSUE TITLE
HBP Server needs testing

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#180]
I HIGHLY recommend the HBP server is tested before release.

We accidentally found a bug that would have made it completely unusable when updated to latest code.
See: https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/170

Are there others?

**Comment by alan-stokes** [comment]
how to test the HBP portal on the other hand is a open ended box. more related to supporting more than 1 version of the tools for the portal. Has the smell of pandora's box

**Comment by rowleya** [comment]
We can test by actually installing it on the portal system, though this requires a little bit of a finesse...

**Comment by andrewgait** [comment]
I'd be happy to look at this in my "user support" sort of role if no-one else has looked at it yet... ?

**Comment by alan-stokes** [comment]
by installing it on the HBP portal, don't we expose the end users to whatever cock ups we've done? what we were thinking was a test state which can test the flow without interfering with end users till we are confident it works. which is why its got a wiff of a Pandora box.

**Comment by rowleya** [comment]
This has been tested using the staging server, so closing now.
