### ISSUE TITLE
C++ compiler *fix*

### ISSUE THREAD

**Issue by chanokin** [SpiNNakerManchester/SpiNNFrontEndCommon#203]
I've added the _-ffreestanding_ option to the compiler flags and the _-nostartfiles_ to the linker. This "fixes" compilation of the connection builder module, though I need to test if the binary is doing what it's supposed to.

**Comment by rowleya** [comment]
Excellent - good to know!  I plan on looking at the integration of this in the coming weeks / months (probably after the summit now)

**Comment by chanokin** [comment]
I checked on a brand new install in a virtual environment and the latest compiler I could find (i.e. 5.4 2016q3) and the binary seem to be doing what it's supposed to.

**Comment by andrewgait** [comment]
If you want to, you can test this out on the latest version (version 6, which came out earlier this year) of the compiler - you can get it at the following link (for Ubuntu):

https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa

If you're using Windows then I believe you can get version 6 there too; as far as I can see, though, you can't get version 6 for MAC OSX yet...

**Comment by chanokin** [comment]
Thanks, @andrewgait, I've tested the compilation and it still works.

BTW the new place for downloads is:
https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

**Comment by andrewgait** [comment]
As far as I can see both these flags are included in the relevant place in spinnaker_tools.mk so I'm going to close this issue.
