### ISSUE TITLE
CodeSubsets do not have attribute Value

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#227]
Error reporting such as:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/interface_functions/chip_provenance_updater.py
__call__

Fill in errors with 
error_cores.values()
Where error_cores comes from the 
https://github.com/SpiNNakerManchester/SpiNNMan/blob/master/spinnman/transceiver.py get_cores_in_state(..

Which returns a:
https://github.com/SpiNNakerManchester/SpiNNMachine/blob/master/spinn_machine/core_subsets.py

Which does not have values() method.

**Comment by alan-stokes** [comment]
this still a issue?

**Comment by rowleya** [comment]
It would appear so - I guess it works because the cores haven't failed... should be fixed at some point though

**Comment by Christian-B** [comment]
Fixed with https://github.com/SpiNNakerManchester/SpiNNMachine/commit/f7565a339e760ecbef75c4aecc9e98977469eb55
