### ISSUE TITLE
Add symbolic link "latest" pointing to the most recent report in simulation reports/ directory

### ISSUE THREAD

**Issue by mmikaitis** [SpiNNakerManchester/SpiNNFrontEndCommon#278]
This would be useful when browsing through those reports in the terminal.

On a mac I get around it by running something like:

fswatch -o reports | rm latest & ln -s reports/`ls -rt reports/| tail -n1` latest

It would be easier if this link is created by the tools, after each simulation is run.

Sorry if this already exists in some other form.

Thanks,

Mantas

**Comment by alan-stokes** [comment]
in the mode where there are multiple runs in parallel on the same machine. which one do you call latest? The answer is that they are all latest. So you cannot have a folder called latest.

This is why we shifted to dated folders and a finished flag inside them to diagnose if the script its associated with has finished (and therefore allow us to clear it away once your max_folders threshold is reached).

therefore this will not be feasible to execute. closing.
