### ISSUE TITLE
extra_monitor_dtcm usage

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#300]
If it comes to light that the re-inejction is struggling with the reduced dumped packet queue resulting from data_out_optimisations branch, it would be possible to dynamically allocate it at the beginning of run, and then data out /data in could free it during their stages and utilise the memory as needed then.

this has not been done, given the slow down that would occur having to send reinejciton start messages. But is left here as a optimisation for possible future bugs.

**Comment by dkfellows** [comment]
Not been an issue we've noticed for 5 years...
