### ISSUE TITLE
PreAllocateResourcesForExtraMonitorSupport does not included ExtraNMonitorSupport SDRAM

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#328]
Noticed then creating a VERY large neuron is the new SDRAM usage models.

**Comment by alan-stokes** [comment]
would fix, but having laptop problems. handing over to christian till i get this laptop fixed.

**Comment by Christian-B** [comment]
Beleived to be working
