### ISSUE TITLE
The ReverseIPTagMulticastSource should be included in auto-pause-and-resume

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/SpiNNFrontEndCommon#337]
When buffering is required to send in data, the ReverseIPTagMulticastSource should make use of the auto-pause-and-resume cycle to ensure that data is correctly injected.  This would avoid issues like #336.  It should still be possible to run without auto-pause-and-resume of course.

**Comment by andrewgait** [comment]
I think this was dealt with when the move over to the new model representation was done.  It certainly seems as though the SpikeSourceArrayVertex works with auto-pause-and-resume...

**Comment by rowleya** [comment]
Yep, done, so closing
