### ISSUE TITLE
Minor BufferManager weirdness

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#346]
Not bugs just weirdness.

The are two variables.
_extra_monitor_cores which is a list of These
_extra_monitor_cores_by_chip which is a map for core to these same cores.

Why not just use
_extra_monitor_cores_by_chip.values ?

**Comment by Christian-B** [comment]
def _request_data(self, transceiver, placement_x, placement_y, address,
                      length):


Why pass in self.Transceiver to a private method?
and then have to do # pylint: disable=too-many-arguments

**Comment by alan-stokes** [comment]
extramonitor cores. i would assume thats first pass vs optimisations. Id just check beforehand where the list is used. I bet the workflow manager includes a few places where only the list is handed over.

_request data txrx. Phft, no idea, would need to have line numbers and look at what calls it.

**Comment by Christian-B** [comment]
Possible optization but best done after release.

**Comment by Christian-B** [comment]
_extra_monitor_cores aka MemoryExtraMonitorVertices is used elsewhere for example HostExecuteApplicationDataSpecification so has to be generated anyway so why not use.
