### ISSUE TITLE
no clear mapping between python and c code recording regions

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#365]
It ust to be that a variable had a given recording id and that it was handed down from python to the c code, thus avoiding mismatch between python and c. now the c has a hardcoded set of #defines which flag the index's, but there is no such fixment in the python, it only occurs due to a ordering of a list. this should instead be sent down to the c code, so that future changes do not cause this to crash.

**Comment by Christian-B** [comment]
That is from long ago. I did not change that.  At least I don't think I did.

**Comment by alan-stokes** [comment]
didnt say ya did. just that it does need fixing, and you've last been there. so ya would be best tailored to fix it. *grins*

**Comment by rowleya** [comment]
Is the set of defines in FEC or should this be a sPyNNaker bug?

**Comment by andrewgait** [comment]
The hardcoded set of defines is in sPyNNaker at https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/neural_modelling/src/neuron/implementations/neuron_impl_standard.h so perhaps this is a sPyNNaker issue really.

**Comment by alan-stokes** [comment]
probabily.
