### ISSUE TITLE
Check router clock speed 

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNFrontEndCommon#419]
Check the stuff to do with router clock speeds in the JSON

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/SpiNNMachine/blob/master/spinn_machine/router.py
ROUTER_DEFAULT_CLOCK_SPEED = 150 * 1024 * 1024

Json:

routerClockSpeed | 157286400


Either this has been fixed or I don't undertsand the problem,

**Comment by rowleya** [comment]
I don't know how much it matters anywhere, but pretty sure the router clock speed is 133Mhz...

**Comment by Christian-B** [comment]
Well then if router.py is that wrong this should be stripped out completely,

**Comment by Christian-B** [comment]
Info incorrect so should be completely stripped out.
