### ISSUE TITLE
Processors RTE/Watchdog on simulation with high fanin to split population

### ISSUE THREAD

**Issue by AlexRast** [SpiNNakerManchester/SpiNNFrontEndCommon#5]
This concerns the benchmarking network attached. The network features a receiver population connected all-to-all with a source population using SpikeSourcePoisson. The source population contains 8192 neurons. All works fine if the size of the receiving population is 255 or less. But if it is more, necessitating a split across cores, you get the error messages as further listed below.

-------------------------------------------------------------------------------------------------------------------------------
File SbEBenchmark.py:

import numpy
import math
import matplotlib.pyplot as py_plot
import matplotlib.colors as colours
from pyNN.spiNNaker_103_3 import *            # Imports the pyNN.spiNNaker module

population_colours = ['#FF0000', '#00FF00', '#0000FF', '#FFFF00', '#FF00FF', '#00FFFF', '#FF8000', '#FF0080', '#800000', '#008000', '#000080', '#808000', '#800080', '#008080', '#804000', '#800040', '#C00000', '#00C000', '#0000C0', '#C0C000', '#C000C0', '#00C0C0', '#C06000', '#C00060', '#400000', '#004000', '#000040', '#404000', '#400040', '#004040', '#402000', '#400020']
colour_map_pop = colours.ListedColormap(colors=population_colours, name='population_colour_label')
colour_range = colours.BoundaryNorm(boundaries=range(len(population_colours)), ncolors=len(population_colours), clip=True)

pop_size = 400
input_pop_size = 8192
input_type = "poisson"
output_type = "lif_curr"
random_weights = False

runtime = 1000.0
stim_start = 0.0
stim_rate = 3.77 #23.23
i_offset_input = 0.0
i_offset_range = 0.5
i_offset_output = 0.0
pops_to_observe = ['inputs', 'outputs']

rng_weights=NumpyRNG(seed=369121518)
rng_currents=NumpyRNG(seed=857201117)
i_init_distr = RandomDistribution('uniform', [i_offset_input-i_offset_range,i_offset_input+i_offset_range], rng_currents)

min_weight = 0.0
max_weight = 5.0
if random_weights:
   weight_dependence_n = RandomDistribution(distribution='uniform', parameters=[1.0+min_weight, 1.0+max_weight], rng=rng_weights)
else:
   weight_dependence_n = max_weight

# Simulation Setup
setup(timestep=1.0, min_delay = 1.0, max_delay = 11.0, db_name='benchmark_SbE.sqlite')
if pop_size > 255 and input_pop_size > 255:
   if output_type == 'izhikevich':
      set_number_of_neurons_per_core(IZK_curr_exp, 255)
   elif output_type == 'lif_cond_exp':
      set_number_of_neurons_per_core(IF_cond_exp, 255)
   else:
      set_number_of_neurons_per_core(IF_curr_exp, 255)

# Neural Parameters
tau_m    = 24.0    # (ms)
cm       = 1
v_rest   = -65.0     # (mV)
v_thresh = -45.0     # (mV)
v_reset  = -65.0     # (mV)
t_refrac = 3.0       # (ms) (clamped at v_reset)
tau_syn_exc = 3.0
tau_syn_inh = tau_syn_exc*3

# cell_params will be passed to the constructor of the Population Object
cell_params_basic = {'tau_syn_E': tau_syn_exc,
                     'tau_syn_I': tau_syn_inh,
                     'v_init' : v_reset,
                     'i_offset': i_offset_output
                    } 
cell_params_izk = {'a': 0.02,
                   'b': 0.2,
                   'c': -65,
                   'd': 8,
                   #'v_init': -75,
                   'u_init': 0,
                   #'tau_syn_E': 2,
                   #'tau_syn_I': 2,
                   #'i_offset': 0
                   }
cell_params_izk.update(cell_params_basic)
cell_params_lif = {'tau_m' : tau_m,
                   'cm' : cm,
                   'v_rest' : v_rest,
                   'v_reset' : v_reset,
                   'v_thresh' : v_thresh,
                   'tau_refrac' : t_refrac, 
              }
cell_params_lif.update(cell_params_basic)
cell_params_lif_cond = {'e_rev_E': 0.,
                        'e_rev_I': -80.
                        #'cm': 0.25,
                        #'i_offset': 0.0,
                        #'tau_m': 20.0,
                        #'tau_refrac': 2.0,
                        #'tau_syn_E': 5.0,
                        #'tau_syn_I': 5.0,
                        #'v_reset': -70.0,
                        #'v_rest': -65.0,
                        #'v_thresh': -50.0,
                   }
cell_params_lif_cond.update(cell_params_lif)
cell_params_const_rate = cell_params_lif.copy()
cell_params_const_rate['i_offset'] = i_offset_input
cell_params_rand_rate = cell_params_lif.copy()
cell_params_rand_rate['i_offset'] = i_init_distr
observed_pop_list = []
if input_type == "poisson":
   inputs = Population(input_pop_size,                                                # size 
                       SpikeSourcePoisson,                                            # Neuron Type
                       {'duration': runtime, 'start': stim_start, 'rate': stim_rate}, # Neuron Parameters
                       label="inputs")                                                # Label
elif input_type == "array":
   inputs = Population(input_pop_size,                      # size                        
                       SpikeSourceArray,              # Neuron Type
                       {'spike_times': data_input_1}, # Neuron Parameters
                       label="inputs")                # Label
elif input_type == "const_rate":
   inputs = Population(input_pop_size,               # size 
                       IF_curr_exp,            # Neuron Type
                       cell_params_const_rate, # Neuron Parameters
                       label="inputs")         # Label
else:
   inputs = Population(input_pop_size,         # size 
                       IF_curr_exp,            # Neuron Type
                       cell_params_rand_rate,  # Neuron Parameters
                       label="inputs")         # Label

if 'inputs' in pops_to_observe:
   inputs.record()
   observed_pop_list.append(inputs)

if output_type == 'izhikevich': 
   outputs = Population(pop_size,          # size 
                        IZK_curr_exp,      # Neuron Type
                        cell_params_izk,   # Neuron Parameters
                        label="outputs")   # Label
elif output_type == 'lif_cond':
   outputs = Population(pop_size,               # size 
                        IF_cond_exp,            # Neuron Type
                        cell_params_lif_cond,   # Neuron Parameters
                        label="outputs")        # Label
else:
   outputs = Population(pop_size,          # size 
                        IF_curr_exp,       # Neuron Type
                        cell_params_lif,   # Neuron Parameters
                        label="outputs")   # Label

if 'outputs' in pops_to_observe:
   outputs.record()
   observed_pop_list.append(outputs)

stimulate_pop_1 = Projection(inputs, 
                             outputs, 
                             AllToAllConnector(weights=weight_dependence_n, delays=1.0), 
                             target='excitatory')

run(runtime)

id_accumulator=0
output_file = open('out_spikes.txt', 'w')
for pop in observed_pop_list:
    state_colour = 0
    data = numpy.asarray(pop.getSpikes())
    #data_by_entry = numpy.swapaxes(data, 0, 1)
    #timed_data = [(data[row][1], data[row][0]) for row in numpy.lexsort(data_by_entry[0,:], data_by_entry[1,:])]
    timed_data = [(data[row][1], data[row][0]) for row in numpy.lexsort((data[:,0], data[:,1]))]
    output_file.write('spike_times for population %s\n' % pop.label)
    output_file.write('time     neuron_id\n')
    for row in timed_data:
        output_file.write('%i   %i\n' % row)
    if len(data) > 0:
       py_plot.scatter(x=data[:,1], y=data[:,0] + id_accumulator, s=8, c=data[:,0], marker='o', cmap=colour_map_pop, norm=colour_range, vmin=0, vmax=32) # s=1, edgecolors='none',
    id_accumulator += pop.size
    id_accumulator += 5
output_file.close()
state_plot = py_plot.gcf()
state_plot.set_frameon(True)        # Background on 
state_plot.set_facecolor('#808080') # A grey background is easiest to see
py_plot.show()

-------------------------------------------------------------------------------------------------------------------------------
File SbE_errors.txt:

2015-06-18 00:29:40 INFO: Read config files: spynnaker.cfg, /home/P06/rasta/folders/prg/gamma_package_103/spynnaker/spynnaker.cfg
2015-06-18 00:29:41 INFO: sPyNNaker (c) 2015 APT Group, University of Manchester
2015-06-18 00:29:41 INFO: Release version 2015.004 - April 2015
2015-06-18 00:29:41 INFO: Setting time scale factor to 1.
2015-06-18 00:29:41 INFO: Setting appID to 30.
2015-06-18 00:29:41 INFO: Setting machine time step to 1000.0 micro-seconds.
2015-06-18 00:29:47 INFO: 72 cores and 20 links
2015-06-18 00:29:48 INFO: *** Running Mapper *** 
started timer
Progress Partitioning the partitionable_graph's vertices
|0                           50%                         100%|
 ============================================================
Progress on partitioning the partitionable_graph's edges
|0                           50%                         100%|
 ============================================================
Progress for placing the partitioned_graphs subvertices
|0                           50%                         100%|
 ============================================================
Progress Allocating Tags
|0                           50%                         100%|
 ============================================================
Progress on checking which subedges are filterable given heuristics
|0                           50%                         100%|
 ============================================================
Progress on allocating the key's and masks for each subedge
|0                           50%                         100%|
 ============================================================
Progress Creating routing entries for each subvertex
|0                           50%                         100%|
 ============================================================
the difference in time between start and sample is 0:00:00.518245
started timer
2015-06-18 00:29:49 INFO: *** Generating Output *** 
Progress on generating data specifications
|0                           50%                         100%|
 ============================================================
the difference in time between start and sample is 0:00:45.749560
started timer
Progress on executing data specifications on the host machine
|0                           50%                         100%|
 ============================================================
the difference in time between start and sample is 0:00:24.504664
started timer
2015-06-18 00:30:59 INFO: *** Loading tags ***
2015-06-18 00:30:59 INFO: *** Loading data ***
Progress Loading application data onto the machine
|0                           50%                         100%|
 ============================================================
Progress Loading routing data onto the machine
|0                           50%                         100%|
 ============================================================
2015-06-18 00:31:42 INFO: *** Loading executables ***
Progress Loading executables onto the machine
|0                           50%                         100%|
 ============================================================
2015-06-18 00:31:43 INFO: *** Loading buffers ***
Progress on initialising the buffer managers for vertices which require buffering
|0                           50%                         100%|
 ============================================================
the difference in time between start and sample is 0:00:44.216711
2015-06-18 00:31:43 INFO: *** Running simulation... *** 
Progress on loading buffer dependant vertices
|0                           50%                         100%|
 ============================================================
2015-06-18 00:31:43 INFO: Starting application
2015-06-18 00:31:43 INFO: Checking that the application has started
2015-06-18 00:31:43 INFO: Application started - waiting 2.0 seconds for it to stop
Traceback (most recent call last):
  File "./SbEBenchmark.py", line 150, in <module>
    run(runtime)
  File "/home/P06/rasta/folders/prg/gamma_package_103/spynnaker/pyNN/__init__.py", line 188, in run
    _spinnaker.run(run_time)
  File "/home/P06/rasta/folders/prg/gamma_package_103/spynnaker/pyNN/spinnaker.py", line 401, in run
    self._time_scale_factor)
  File "/home/P06/rasta/folders/prg/gamma_package_103/spinn_front_end_common/interface/front_end_common_interface_functions.py", line 332, in _wait_for_execution_to_complete
    "breakdown {}.".format(processors_rte, break_down))
spinn_front_end_common.utilities.exceptions.ExecutableFailedToStopException: 1 cores have gone into a run time error state with breakdown 
1:0:1 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:2 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:3 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:4 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:5 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:6 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:7 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:8 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:9 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:10 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:11 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:12 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:13 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:14 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:15 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:1 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:2 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:3 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:4 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:5 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:6 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:7 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:8 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:9 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:10 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:11 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:12 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:13 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:14 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:15 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:16 failed to be in state CPUState.RUNNING and was in state FINSHED instead
0:0:17 failed to be in state CPUState.RUNNING and was in state FINSHED instead
1:0:16 failed to be in state CPUState.RUNNING and was in state WATCHDOG instead
1:0:17 failed to be in state CPUState.RUNNING and was in state RUN_TIME_EXCEPTION:DABT instead
.

**Comment by rowleya** [comment]
I have tried running this example with the latest git version of the tools.  It seems to work fine.  If you are also using the git version, it is worth attempting a rebuild of the binaries to ensure that nothing has changed.  I will close this issue for now, but feel free to reopen it if you feel that it is still a problem.
