### ISSUE TITLE
ds_pretend_database in FUBAR

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#521]
this class located in fec->interface->ds->ds_pretend_database is not used by anything that i can see. But what adds insult to injury is that it cant be instantiated as its missing at least 2 abstract methods (clear_ds, ds_mark_as_system) (i will be adding a third shortly) which means its usage is already broken. 

can we remove or do we need to fix it?

**Comment by alan-stokes** [comment]
whilst i'm at it. why have a abstract (ds_abstract_database) if only 1 thing inherits from it?

**Comment by Christian-B** [comment]
Accidentally fixed straight to master:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/commit/4ca70f9251466e78cdb65b1d37487768ffcfb45e

**Comment by Christian-B** [comment]
Update checked by @alan-stokes so closing issue.
