### ISSUE TITLE
get_current_time after runforver

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#534]
if a run forever has happened and no reset has been called.

How should get_current_time act?

Currently it raises some kind of None exception

Assigen to @Christian-B with the desired behaviour

**Comment by alan-stokes** [comment]
honestly. id say it should just return None and a log warning with something along of the lines of "When running forever, it is not possible to determine the current runtime". 

Id also argue that when end is called after a run forever, it shoudl also return the same message, as until we implement some way to ensuring all cores are at a given timestep when pausing in a none auto pause and resume manner, it is not possible.

**Comment by Christian-B** [comment]
In https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/929 the choice was made to return 0.0
