### ISSUE TITLE
Allow gathering of provenance without writing it

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/SpiNNFrontEndCommon#578]
There is currently only one provenance option, which is to "write_provenance_data".  It would be useful if there was a "read_provenance_data" which would get and evaluate the provenance data (i.e. print warnings) without then storing it.  This could be useful when there is a lot of data and storage would be prohibitive.

**Comment by alan-stokes** [comment]
fair enough.

**Comment by alan-stokes** [comment]
does this still count given the prov via database fixes?

**Comment by alan-stokes** [comment]
isnt this done now?

**Comment by rowleya** [comment]
No, I think it is still written to the database.  It should be possible to store it in memory and then use it in the top-level script.

**Comment by alan-stokes** [comment]
ok. so this is coz we use the write_prov config to control both the addition of the algoirtmhs, and the writing to whatever writer we set up to use. 

so a extra cfg param for reading them would solve that. 

i note that lines 2640 - 2657 and 1888 - 1909 are near clones of each other. i admit 1 tries to read the power mon prov. but if it didnt exist it would still work. so id assume it would be possible to strip them into 1 method for saving some lines. 

anyhow. might do this when got a bit of slack

**Comment by alan-stokes** [comment]
closing this now that the fix is in. no idea why github didn't automatically do so. 
reopen if someone disagrees
