### ISSUE TITLE
provenance database almost unreadable

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#603]
One of the things that the file system had which was good. was that it separated the bits of prov into individual files. 

in the database, maybe it should be augmented to have the equiv views that we would have in files. so that its easy to get to what the end user wants to read?

**Comment by Christian-B** [comment]
Look into adding core info (x,y,p)

**Comment by andrewgait** [comment]
I think this is what was done in e.g. https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/652 - is there anything more needed on top of that?

**Comment by alan-stokes** [comment]
i added the views in a previous pr that got accepted by donal a bit ago. so i guess we can shut this down now
