### ISSUE TITLE
building ReverseIPTagMulticastSourceMachineVertex directly has issues with partitions

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#630]
If you build a ReverseIPTagMulticastSourceMachineVertex in GFE and then add multiple outgoing egde partitions. the ReverseIPTagMulticastSourceMachineVertex will seledct the key from whatever is the first from :

                partitions = machine_graph\
                    .get_outgoing_edge_partitions_starting_at_vertex(self)
                partition = next(iter(partitions), None)

in lines 600 to 603. there is no check to see if there are multiple. at which point it should go BOOM!

**Comment by Christian-B** [comment]
This has not been an issue so far.

The correct fix will depend on the exact usage so lets worry about it when we have that usage.
