### ISSUE TITLE
pair compressor recursion sorts makes it go boom boom 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#651]
When using vogals and the pair compressor with bitfields. the first sort (which is recursive) makes the entire machine go boom.

the sorts need to be rewritten to be none recursive for safety (even if it slows it down)

**Comment by andrewgait** [comment]
This was fixed by https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/653, so closing.
