### ISSUE TITLE
Add a LivePacketGatherer per board

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/SpiNNFrontEndCommon#69]
Instead of having the live output go to the boot chip, there should be one on each board.  This may require changes to the way the system currently works - one idea is:
1. Add a LivePacketGatherer per board with a placement constraint to put in on the Ethernet chip.  
2. Add an interface for vertices which require live output e.g. RequiresLiveOutput but don't add an edge to a LivePacketGatherer yet.
3. After placement and before routing, run an algorithm that for each vertex that implements RequiresLiveOutput adds an edge to the LivePacketGatherer on the board on which the vertex was placed.

**Comment by alan-stokes** [comment]
done
