### ISSUE TITLE
Prereseve the port of the BufferManager and use this in the tag

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/SpiNNFrontEndCommon#70]
The port of the BufferManager is fixed using the config file.  The BufferManager should instead open a listening connection in advance without specifying a port and then use the port allocated in the IPTag request.

**Comment by alan-stokes** [comment]
pull requests [
SpiNNakerManchester/SpiNNFrontEndCommon/#81
SpiNNakerManchester/sPyNNaker/#254
SpiNNakerManchester/SpiNNMan/#60
SpiNNakerManchester/PACMAN/#61
SpiNNakerManchester/SpiNNMachine/#24
SpiNNakerManchester/IntroLab/#2
 ] are all related to this issue. And therefore is now awaiting review

**Comment by alan-stokes** [comment]
done
