### ISSUE TITLE
If both graphs are empty should we use the app graph?

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#708]
Currently in AbstractSpinnakerBase,_do_mapping if the user has added to neither the application or the machine graph BOTH empty graphs are passed to functions like InsertExtraMonitorVerticesToGraphs

This then results in the exta monitors being added to both graphs.

Is this desirable?

**Comment by rowleya** [comment]
I would suggest that if all graphs are empty when the user calls run, that nothing should happen i.e. the call should return instantly.  It doesn't need to fail, just do exactly what it was asked, which is nothing.

**Comment by alan-stokes** [comment]
concur

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/707
