### ISSUE TITLE
Support dynamically allocated external visualiser ports

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/SpiNNFrontEndCommon#71]
The database notification protocol should be extended to be able to listen for ports to be registered by external receivers which can then be used in the tags of those receivers.  The label of the vertex can be used to map between the external receiver and the IPTag required.
1. A script contains a vertex which is to send live output but without a pre-determined port (or IP address).  The vertex calls the registration interface to request the port with the vertex label and is blocked until a port has been determined.
2. A registration socket listens on a pre-determined or dynamically allocated port (which is then printed to the screen) for a message from an external listener containing a port and a label.
3. An external listener opens a socket without a pre-determined port and then finds out the port number and sends this to the registration socket along with the IP address it is listening on and vertex label to be listened to.
4. The registration socket enables the registration interface to send the port number back to the vertex which then requests an IPTag with the appropriate port and IP address.

Note that this interface should be entirely complementary to the existing database interface.  Should the port number be pre-determined, it shouldn't be necessary to wait for the registration interface.

**Comment by dkfellows** [comment]
I've no idea how this would interact with how we do things now (with proxying, etc.) but the protocol as outlined above sounds confusing to me. It's not going to happen as laid out.
