### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by andrewgait** [SpiNNakerManchester/SpiNNFrontEndCommon#739]
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/141be356a38c74cc9d1d04381a92b43184040fb6/c_common/models/compressors/src/bit_field_compressor.c#L339

I think it should be 

`        } else if (comms_sdram->sorter_instruction == DO_NOT_USE) {`

instead, but flagging it for someone else to check.

**Comment by Christian-B** [comment]
Issue is correct but only thing that will change is the last log message on compressor cores no longer needed.

Will fix
