### ISSUE TITLE
helpful functions is starting to steal code from its logcal place

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNFrontEndCommon#743]
def write_address_to_user0(txrx, x, y, p, address):
def write_address_to_user1(txrx, x, y, p, address):
def read_data(x, y, address, length, data_format, transceiver):

all these seem to really be things that should reside in txrx.

**Comment by Christian-B** [comment]
convert_string_into_chip_and_core_subset should go into CoreSubsets

**Comment by Christian-B** [comment]
read_config... into ConfigHandler

**Comment by Christian-B** [comment]
get_ethernet_chip into MAchine
