### ISSUE TITLE
Add jar option to config

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/SpiNNFrontEndCommon#782]
Make it possible for the user to specify just the path of the jar file when using Java.  Currently the jar file has to reside in various subfolders for it to be picked up (which works for development more than for production releases).

**Comment by Christian-B** [comment]
If a jar path is specified in the cfg and there is also a jar either in the expect place or via the java_spinnaker_path which should it pick.

My preference is to raise an exception asking the user to either delete the jar cfg setting or the jar built locally
