### ISSUE TITLE
Cleaup of tags allocation and loading

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#786]
The BasicTagAllocator outputs the Tags Object
But also its ip_tags and reverse_ip_tags properties separately.

As:
            <param_type>MemoryIpTags</param_type>
            <param_type>MemoryReverseIpTags</param_type>
            <param_type>MemoryTags</param_type>

The only place the separate where used appears to be:
 <algorithm name="TagsLoaderSeparateLists"> which calls
spinn_front_end_common.interface.interface_functions.TagsLoader

BUT:
TagsLoaderSeparateLists"
requires:
<param_type>MemoryIpTags</param_type>
<param_type>MemoryReverseTags</param_type>
<param_type>MemoryTransceiver</param_type>

So could never be used anyway.

Proposal.
Simplify BasicTagAllocator and TagsLoader to only use tags.
Nuke the TagsLoaderSeparateLists agorithm.

**Comment by rowleya** [comment]
Agreed!
