### ISSUE TITLE
Is is possible to remove the injector.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#817]
To remove or not to remove injection that is the question.

The known uses for the injector currently are:
APPID 
(Memory)ApplicationGraph 
DataInMulticastKeyToChipMap
DataNTimeSteps/ DataNSteps 
(Memory)ExtendedMachine 
FirstMachineTimeStep
(Memory)MachineGraph
MachinePartitionNKeysMap
(Memory)Placements
(Memory)RoutingInfos 
RunUntilTimeSteps
SystemMulticastRouterTimeoutKeys
MemoryTags 
plus 
MachineTimeStep, and TimeScaleFactor which are being removed in a PR

With a bit of work it would be possible to replace these with calls of the type
global_variables.get_simulator().placements
or semantic sugar for that with or without safety code.

These are likely to be faster than injector calls but that should not be the reason to do this.

The easiest are the ones where ASB already holds the data in a variable
APPID, ApplicationGraph, DataNTimeSteps/DataNSteps, FirstMachineTimeStep, MachineGraph, Placements, and Tags
 
DataInMulticastKeyToChipMap, MachinePartitionNKeysMap, RoutingInfos, and SystemMulticastRouterTimeoutKeys are currently not held in ASB but could easily be.

ExtendedMachine is slightly trickier in that ASB does have machine but it needs the virtual chips added to be an "ExtendedE machine

RunUntilTimeSteps is the one that needs the most care as it could be either max timesteps to load in case we run again / the current runtimesteps

-----
Unlike MachineTimeStep, and TimeScaleFactor which are fixed during setup, these object are created by other algorithms so without care we would loose the checking that injection adds.

---
In my opinion removing all but a few hard cases is not really the best approach.
Either only do the clear ones like  MachineTimeStep, and TimeScaleFactor or do all to remove the whole injection overhead.

**Comment by dkfellows** [comment]
There is sugar for the placements getting in the GFE, especially for the common case where a machine vertex wants it's own placement.

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/929
