### ISSUE TITLE
Split AbstractSpinnakerBase into model(s), view(s), controller(s)

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#848]
Currently AbstractSpinnakerBase and  its children include
1. Data
2. methods to access data
3. methods to run algorithms
4. methods for users
5. methods for alogirthms
ect

Idea wuld be to split this into several smaller separate classes

**Comment by Christian-B** [comment]
Together with https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/849 it can be considered which data needs to go into the model and what is just pass through bwteeen algorithms

**Comment by dkfellows** [comment]
How much of this is still relevant?

**Comment by Christian-B** [comment]
With the data objects being moved to the views this is a lot less import.

As the software team will be significantly reduced do to the end of the HBP project this is now a "Will not do"
