### ISSUE TITLE
CommandSender vertex not added after hard reset

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#860]
The ASB method _add_commands_to_command_sender
Looks to see if a CommandSender vertex is needed and if so adds it to the graph

is then saves the CommandSender as self._command_sender

On a second call to _add_commands_to_command_sender there will be a new graph
However as self._command_sender exists no CommandSender is added the second time.

I think the fix is to replace self._command_sender with a local variable in  _add_commands_to_command_sender as it the value is never used outside of that method.

**Comment by rowleya** [comment]
The fix sounds about right; so long as one gets added to each graph it should be OK
