### ISSUE TITLE
execute_system_data_specs vs execute_application_data_specs

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNFrontEndCommon#873]
There are separate methods for loading system vs application data specs.

Without looking I note it may be worth reviewing if both are needed or if one pass can do both.

May well be a good reason in which case both are kept.

**Comment by rowleya** [comment]
Simple reason is that you want to load data for, and execute, system binaries so that these can be used to run the fast loading data protocol which then loads the application data (which is normally much bigger).

**Comment by Christian-B** [comment]
good reason!
